[db.migrations]
schema_paths = [
  "./schemas/setup.sql",           # Setup first: enums, schemas, permissions
  "./schemas/tables/0[0-9]_*.sql", # All table definitions in order
  "./schemas/functions.sql",       # Database functions
  "./schemas/triggers.sql",        # Database triggers  
  "./schemas/policies.sql",        # RLS policies
  "./schemas/views.sql"           # Views and computed tables
]

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = []
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 3600 